version: '3'
services:
  php:
    build: ./php
    restart: always
    volumes:
      - ../../PHP:/var/www/html
    ports:
      - "8001:80"
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - lamp_db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: piriyala
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmymadin
    links:
      - db:db
    restart: always
    ports:
      - "8000:80"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
volumes:
  lamp_db: